create table app_users (
    id bigint generated by default as identity primary key,
    email varchar(255) not null,
    password_hash varchar(255) not null,
    role varchar(32) not null,
    enabled boolean not null default true,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uq_app_users_email unique (email),
    constraint ck_app_users_role check (role in ('CUSTOMER', 'PROVIDER', 'ADMIN'))
);

create table providers (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    business_name varchar(255) not null,
    description varchar(1000),
    category varchar(120) not null,
    city varchar(120) not null,
    address varchar(255),
    active boolean not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_providers_user foreign key (user_id) references app_users (id),
    constraint uq_providers_user unique (user_id)
);

create table offered_services (
    id bigint generated by default as identity primary key,
    provider_id bigint not null,
    name varchar(255) not null,
    description varchar(1000),
    duration_minutes integer not null,
    price_cents integer not null,
    active boolean not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_offered_services_provider foreign key (provider_id) references providers (id),
    constraint uq_offered_services_id_provider unique (id, provider_id),
    constraint uq_offered_services_provider_name unique (provider_id, name),
    constraint ck_offered_services_duration check (duration_minutes > 0),
    constraint ck_offered_services_price check (price_cents >= 0)
);

create table availabilities (
    id bigint generated by default as identity primary key,
    provider_id bigint not null,
    service_id bigint not null,
    day_of_week smallint not null,
    start_time time not null,
    end_time time not null,
    active boolean not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_availabilities_provider foreign key (provider_id) references providers (id),
    constraint fk_availabilities_service_provider foreign key (service_id, provider_id) references offered_services (id, provider_id),
    constraint ck_availabilities_day check (day_of_week between 1 and 7),
    constraint ck_availabilities_interval check (end_time > start_time)
);

create table bookings (
    id bigint generated by default as identity primary key,
    customer_id bigint not null,
    provider_id bigint not null,
    service_id bigint not null,
    starts_at timestamp with time zone not null,
    ends_at timestamp with time zone not null,
    status varchar(32) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_bookings_customer foreign key (customer_id) references app_users (id),
    constraint fk_bookings_provider foreign key (provider_id) references providers (id),
    constraint fk_bookings_service_provider foreign key (service_id, provider_id) references offered_services (id, provider_id),
    constraint ck_bookings_interval check (ends_at > starts_at),
    constraint ck_bookings_status check (status in ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELLED', 'COMPLETED'))
);

create table notifications (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    type varchar(64) not null,
    payload text not null,
    status varchar(32) not null,
    created_at timestamp with time zone not null,
    constraint fk_notifications_user foreign key (user_id) references app_users (id),
    constraint ck_notifications_status check (status in ('PENDING', 'SENT', 'FAILED'))
);

create table audit_logs (
    id bigint generated by default as identity primary key,
    actor_user_id bigint,
    event_type varchar(120) not null,
    entity_type varchar(120) not null,
    entity_id bigint,
    payload text,
    created_at timestamp with time zone not null,
    constraint fk_audit_logs_actor foreign key (actor_user_id) references app_users (id)
);

create index idx_providers_category_city on providers (category, city);
create index idx_offered_services_provider on offered_services (provider_id);
create index idx_availabilities_provider_service_day on availabilities (provider_id, service_id, day_of_week);
create index idx_bookings_customer_starts_at on bookings (customer_id, starts_at);
create index idx_bookings_provider_interval on bookings (provider_id, starts_at, ends_at);
create index idx_notifications_user_created_at on notifications (user_id, created_at);
create index idx_audit_logs_entity on audit_logs (entity_type, entity_id);
