create table availability_exceptions (
    id bigint generated by default as identity primary key,
    provider_id bigint not null,
    service_id bigint,
    starts_at timestamp with time zone not null,
    ends_at timestamp with time zone not null,
    reason varchar(255),
    active boolean not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_availability_exceptions_provider foreign key (provider_id) references providers (id),
    constraint fk_availability_exceptions_service_provider foreign key (service_id, provider_id) references offered_services (id, provider_id),
    constraint ck_availability_exceptions_interval check (ends_at > starts_at)
);

create index idx_availability_exceptions_provider_interval on availability_exceptions (provider_id, starts_at, ends_at);
